name: Renovate
on:
  pull_request:
  workflow_dispatch:
    inputs:
      log-level:
        description: "Set the Renovate log level (default: info)"
        required: false
        default: info
        type: choice
        options:
          - info
          - debug
  schedule:
    - cron: '3 * * * *'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Validate Renovate config with schema validator
        run: |
          docker run --rm -v $(pwd):/usr/src/app ghcr.io/renovatebot/renovate:42 \
            renovate-config-validator --strict \
            /usr/src/app/renovate.json \
            /usr/src/app/renovate-shared-config.json \
            /usr/src/app/renovate-config.js

  renovate:
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name != 'pull_request'
    steps:
      - name: Generate Actions Token
        id: token
        if: github.repository_owner == 'bootc-dev'
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v6

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v44.2.3
        env:
          RENOVATE_DRY_RUN: ${{ github.repository_owner != 'bootc-dev' && 'full' }}
          LOG_LEVEL: ${{ github.event.inputs.log-level || 'info' }}
        with:
          configurationFile: renovate-config.js
          token: '${{ steps.token.outputs.token || secrets.GITHUB_TOKEN }}'
